name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Import GPG key
        id: import_gpg
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg_private_key.asc
          echo "${{ secrets.PASSPHRASE }}" > gpg_private_key.passphrase
          gpg --batch --passphrase-file gpg_private_key.passphrase --import gpg_private_key.asc
          rm -f gpg_private_key.asc gpg_private_key.passphrase
          echo "::set-output name=fingerprint::$(gpg --list-secret-keys --keyid-format LONG | grep rsa | awk -F ' ' '{print $2}' | awk -F '/' '{print $2}')"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
